function mySmoothStructures(subs, smmm, DATAdir, SHOW,hemi)
fsp = filesep;
disp(['Smoothing factor: ' smmm]);
SHOW = 0;
for ns = 1: length(subs)
    sub = subs(ns).name;
    fnames = fieldnames(subs(ns));
    
for ii = 2:length(fnames)
    % for ii =28:55
        fname = fnames{ii};
        switch fname
            case {'BEHAV_ld'}
                if SHOW 
                    disp('BEHAV: dont do anything... ')
                    disp(' ...done')
                end
            case {'CT'}
                fileIn = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.thickness.fsaverage.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.thickness.fsaverage.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
                
            case{'CURV'}
                fileIn = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.curv.fsaverage.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.curv.fsaverage.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end

            case{'DWI_vOF', 'DWI_pARC'}
                if SHOW 
                    disp('DWI: dont do anything... ')
                    disp(' ...done')
                end
                
            case {'VOT_block_RWvsCB','VOT_block_RWvsCS','VOT_block_RWvsFF', ...
                  'VOT_block_RWvsPS','VOT_block_RWvsPW','VOT_block_RWvsSD', ...
                  'VOT_event_RWvsCB','VOT_event_RWvsCS','VOT_event_RWvsFF', ...
                  'VOT_event_RWvsPS','VOT_event_RWvsPW','VOT_event_RWvsSD', ...
                  'VOT_event_RWvsNull','VOT_block_RWvsNull'}
                design = fname(5:9);
                cont = fname(11:end);
                fileIn = [DATAdir fsp 'fMRI_VOT' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp 'fMRI_VOT' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
            case {'PPC_block_RWvsCB','PPC_block_RWvsCS','PPC_block_RWvsFF', ...
                  'PPC_block_RWvsPS','PPC_block_RWvsPW','PPC_block_RWvsSD', ...
                  'PPC_event_RWvsCB','PPC_event_RWvsCS','PPC_event_RWvsFF', ...
                  'PPC_event_RWvsPS','PPC_event_RWvsPW','PPC_event_RWvsSD', ...
                  'PPC_event_RWvsNull','PPC_block_RWvsNull'}
                design = fname(5:9);
                cont = fname(11:end);
                fileIn = [DATAdir fsp 'fMRI_PPC' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp 'fMRI_PPC' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
            case {'IFG_block_RWvsCB','IFG_block_RWvsCS','IFG_block_RWvsFF', ...
                  'IFG_block_RWvsPS','IFG_block_RWvsPW','IFG_block_RWvsSD', ...
                  'IFG_event_RWvsCB','IFG_event_RWvsCS','IFG_event_RWvsFF', ...
                  'IFG_event_RWvsPS','IFG_event_RWvsPW','IFG_event_RWvsSD', ...
                  'IFG_event_RWvsNull','IFG_block_RWvsNull'}
                design = fname(5:9);
                cont = fname(11:end);
                fileIn = [DATAdir fsp 'fMRI_IFG' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp 'fMRI_IFG' fsp design fsp sub ...
                                       fsp 'results' fsp cont '305.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end             
                
            case{'qMRI_MTV', 'qMRI_T1qMRI'}
                qM = fname(6:end);
                fileIn = [DATAdir fsp 'qMRI' fsp sub fsp ...
                            'OutPutFiles_1' fsp 'BrainMaps' fsp qM '_305.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp 'qMRI' fsp sub fsp ...
                               'OutPutFiles_1' fsp 'BrainMaps' fsp qM '_305.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
                
            case{'qMRI_MTV_WM', 'qMRI_T1qMRI_WM'}
                qM = fname(6:end);
                fileIn = [DATAdir fsp 'qMRI_WM' fsp sub fsp ...
                            'OutPutFiles_1' fsp 'BrainMaps' fsp qM '_305.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp 'qMRI_WM' fsp sub fsp ...
                               'OutPutFiles_1' fsp 'BrainMaps' fsp qM '_305.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
                
            case {'VOL'}
                fileIn = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.volume.fsaverage.mgh'];
                if exist(fileIn, 'file')
                    fileOut = [DATAdir fsp fname fsp sub fsp 'surf' fsp ...
                                hemi '.volume.fsaverage.fhmw' smmm '.mgh'];
                    cmdsmooth = ['mri_surf2surf ' ...
                                 '--hemi ' hemi ' ' ...
                                 '--s fsaverage ' ...
                                 '--sval ' fileIn ' ' ...
                                 '--fwhm ' smmm ' ' ...
                                 '--cortex ' ...
                                 '--tval ' fileOut];
                    system(cmdsmooth)
                else
                    disp([sub ' ' fname ': file doesnt exist'])
                end
            otherwise
                disp([fname ': Unknown field'])
        end    
    end
end

end